version: '3'
services:

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=eweed
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
  
  hpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=admin1234

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:admin

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD:asdmin
      - ME_CONFIG_MONGODB_SERVER:mongo